# Generated by Django 5.2.7 on 2025-12-31 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursecontent_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='instructor',
        ),
    ]
