# Generated by Django 5.2.7 on 2025-12-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_mockinterview_studentproject_weeklytest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterview',
            name='interview_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
