# Generated by Django 5.2.7 on 2025-12-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_mockinterview_interview_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytest',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
