# Generated by Django 5.2.7 on 2025-12-31 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_coursecontent_instructor'),
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='courses.course'),
            preserve_default=False,
        ),
    ]
