# Generated by Django 5.2.7 on 2025-12-31 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_coursecontent_instructor'),
        ('placements', '0003_alter_placement_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='courses.course'),
        ),
    ]
