# Generated by Django 5.2.7 on 2025-12-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LMS Portal', max_length=100)),
                ('support_email', models.EmailField(default='support@example.com', max_length=254)),
                ('allow_self_registration', models.BooleanField(default=True)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('max_courses_per_instructor', models.IntegerField(default=10)),
                ('course_approval_required', models.BooleanField(default=False)),
                ('min_completion_percent', models.IntegerField(default=70)),
                ('auto_generate_certificates', models.BooleanField(default=True)),
                ('quiz_pass_percent', models.IntegerField(default=50)),
                ('max_quiz_attempts', models.IntegerField(default=3)),
                ('default_dark_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
